### ISSUE TITLE
Small Gap just at the bottom & right side of the main section of the image section, if you can fix that would be a great help!

### ISSUE THREAD

**Issue by anshu189** [anshu189/Web-Dev-30#2]
**Note: Do not change the background image URL!**

**Comment by nikgautamgithub** [comment]
The issue of the small gap is fixed!
Additionally, I aligned the text because it was also creating a small gap when the screen size tends to be small.
You can check the file! I have issued a Pull request.

**Comment by anshu189** [comment]
Thanks!
